export const galleryImages = [
  {
    slug: "sway1",
    src: "/images/gallery/sway-001.jpg",
    title: "Performance Night",
    location: "Lagos, Nigeria",
    date: "March 2026",
    description: "Live performance by Sway Charmz.",
  },
  {
    slug: "sway2",
    src: "/images/gallery/sway-002.jpg",
    title: "Studio Session",
    location: "Studio",
    date: "2026",
    description: "Recording new music.",
  },
  {
    slug: "sway3",
    src: "/images/gallery/sway-003.jpg",
    title: "Behind The Scenes",
    location: "Backstage",
    date: "2026",
    description: "Preparing before a performance.",
  },
  {
    slug: "sway4",
    src: "/images/gallery/sway-004.jpg",
    title: "Portrait",
    location: "Photoshoot",
    date: "2026",
    description: "Official artist portrait.",
  },
  {
    slug: "sway5",
    src: "/images/gallery/sway-005.jpg",
    title: "Live Crowd",
    location: "Concert",
    date: "2026",
    description: "Connecting with the audience.",
  },
  {
    slug: "sway6",
    src: "/images/gallery/sway-006.jpg",
    title: "Late Night Studio",
    location: "Recording Studio",
    date: "2026",
    description: "Creating new sounds.",
  },
  {
    slug: "sway7",
    src: "/images/gallery/sway-007.jpg",
    title: "Music Video Shoot",
    location: "On Set",
    date: "2026",
    description: "Filming the latest music video.",
  },
  {
    slug: "sway8",
    src: "/images/gallery/sway-008.jpg",
    title: "Collaboration Session",
    location: "Studio",
    date: "2026",
    description: "Working with other artists.",
  },
  {
    slug: "sway9",
    src: "/images/gallery/sway-009.jpg",
    title: "Album Artwork Design",
    location: "Design Studio",
    date: "2026",
    description: "Creating visuals for the album.",
  },
  {
    slug: "sway10",
    src: "/images/gallery/sway-010.jpg",
    title: "Fan Interaction Event",
    location: " Meet & Greet",
    date: "2026",
    description: "Engaging with fans.",
  },
  {
    slug: "sway11",
    src: "/images/gallery/sway-011.jpg",
    title: "Rehearsal",
    location: "Practice Space",
    date: "2026",
    description: "Preparing for the next show.",
  },
  {
    slug: "sway12",
    src: "/images/gallery/sway-012.jpg",
    title: "Award Ceremony",
    location: "Event Hall",
    date: "2026",
    description: "Receiving recognition for achievements.",
  },
  {
    slug: "sway13",
    src: "/images/gallery/sway-013.jpg",
    title: "Recording Session",
    location: "Studio",
    date: "2026",
    description: "Capturing new tracks.",
  },
  {
    slug: "sway14",
    src: "/images/gallery/sway-014.jpg",
    title: "Touring",
    location: "Various Locations",
    date: "2026",
    description: "On the road for performances.",
  },
  {
    slug: "sway15",
    src: "/images/gallery/sway-015.jpg",
    title: "Press Event",
    location: "Media Center",
    date: "2026",
    description: "Interacting with the press.",
  },
];